export const VIDEO_ITEMS = [
  {
    title: '25 Years of Partnership | Gates Foundation',
    videoId: 'v=T_bIUw7GdTU',
    category: 'brands',
    description: '',
  },
  {
    title: 'BMW Films',
    videoId: 'wTjB4bLzHKo',
    category: 'brands',
    description: 'Premium motorcycle brand campaign',
  },
  {
    title: 'Premium Automotive',
    videoId: '1ZVsxIGs1Kg',
    category: 'brands',
    description: 'Luxury car brand showcase',
  },
  {
    title: 'Corporate Identity',
    videoId: 'lyBQYLtnKdM',
    category: 'brands',
    description: 'Corporate brand storytelling',
  },
  {
    title: 'MamaEarth Campaign',
    videoId: 'eHpSFNNhn2s',
    category: 'brands',
    description: 'Natural skincare brand film',
  },
  {
    title: 'IDBI Federal Marathon',
    videoId: 'Ll846ArEzAQ',
    category: 'events',
    description: 'Major sports event coverage',
  },
  {
    title: 'Corporate Event',
    videoId: 'R_-MOeWMfvU',
    category: 'events',
    description: 'Professional event documentation',
  },
  // {
  //   title: 'Business Event',
  //   videoId: 'NvVb90pZma8',
  //   category: 'events',
  //   description: 'Corporate gathering highlights',
  // },
  {
    title: 'Backpackers',
    videoId: 'a5rx0gaw7q0',
    category: 'shows',
    description: 'Travel adventure series',
  },
  // {
  //   title: 'Industry Event',
  //   videoId: 'LIwleNZaumw',
  //   category: 'events',
  //   description: 'Business conference coverage',
  // },
  {
    title: 'Product Launch',
    videoId: 'PmX_y3ApaDs',
    category: 'brands',
    description: 'New product unveiling event',
  },
  {
    title: 'Music Production',
    videoId: 'xVWPOQwVlNE',
    category: 'music',
    description: 'Hip-hop music video',
  },
  {
    title: 'Thana Sadar',
    videoId: 'cIGYh-SQjkA',
    category: 'shows',
    description: 'Drama series production',
  },
  // {
  //   title: 'Brand Story',
  //   videoId: '_QY7YDY7jPQ',
  //   category: 'brands',
  //   description: 'Corporate brand narrative',
  // },
  {
    title: 'Modern Parivar',
    videoId: 'gJCenfE8qOg',
    category: 'shows',
    description: 'Family drama series',
  },
  {
    title: 'Corporate Film',
    videoId: '4P_0BSWME5E',
    category: 'brands',
    description: 'Business showcase video',
  },
  {
    title: 'Roomies Season 3',
    videoId: 'C8RKIBQoEng',
    category: 'shows',
    description: 'Comedy web series',
  },
  {
    title: 'Marketing Campaign',
    videoId: '8rmFk1dHb_M',
    category: 'brands',
    description: 'Brand marketing film',
  },
  {
    title: 'Product Campaign',
    videoId: 'BoUIN4WyCO0',
    category: 'brands',
    description: 'Product promotional video',
  },
  {
    title: 'Brand Event',
    videoId: 'HGBksIItYQs',
    category: 'events',
    description: 'Corporate event highlights',
  },
  {
    title: 'Corporate Series',
    videoId: 'CdBX0NTjlII',
    category: 'brands',
    description: 'Business documentary series',
  },
  {
    title: 'Innovation Showcase',
    videoId: 'ycD5rQc-_EU',
    category: 'brands',
    description: 'Technology innovation film',
  },
  {
    title: 'Corona Heist',
    videoId: 'bpGCTZYfQG0',
    category: 'films',
    description: 'Short film production',
  },
  {
    title: 'Brand Campaign',
    videoId: 'ea2oVP1U4Fw',
    category: 'brands',
    description: 'Strategic brand campaign',
  },
  {
    title: 'Music Video Project',
    videoId: 'RTCcswAXtn0',
    category: 'music',
    description: 'Professional music video',
  },
  {
    title: 'Corporate Vision',
    videoId: '9hIyf0FyYZ0',
    category: 'brands',
    description: 'Company vision film',
  },
  {
    title: 'Strategic Initiative',
    videoId: 'N3uvC_gRTlc',
    category: 'brands',
    description: 'Business strategy showcase',
  },
  // {
  //   title: 'Corporate Showcase',
  //   videoId: '672438476',
  //   category: 'brands',
  //   description: 'Brand showcase',
  //   platform: 'vimeo',
  // },
  // {
  //   title: 'Brand Vision',
  //   videoId: '571724076',
  //   category: 'brands',
  //   description: 'Corporate film',
  //   platform: 'vimeo',
  // },
  {
    title: 'Unmaad',
    videoId: 'kNTT4n67Ofs',
    category: 'films',
    description: 'Feature film production',
  },
  // {
  //   title: 'Brand Story',
  //   videoId: 'qXAUCQp2xcw',
  //   category: 'brands',
  //   description: 'Corporate storytelling',
  // },
  {
    title: 'Music Production',
    videoId: 'o21H1tiTKOM',
    category: 'music',
    description: 'Professional music video',
  },
  {
    title: 'Brand Campaign',
    videoId: 'N2auTayZ978',
    category: 'brands',
    description: 'Marketing campaign film',
  },
  {
    title: 'Corporate Event',
    videoId: 'dSOrly9zAkk',
    category: 'events',
    description: 'Business event coverage',
  },
  {
    title: 'Great Wall Motors',
    videoId: '70l-Cs1iMLw',
    category: 'brands',
    description: 'Automotive brand campaign',
  },
  {
    title: 'Marketing Initiative',
    videoId: 'MoQCWKwzqxs',
    category: 'brands',
    description: 'Strategic marketing film',
  },
  {
    title: 'Brand Experience',
    videoId: 'DV1tXKLrKPM',
    category: 'brands',
    description: 'Experiential marketing film',
  },
  {
    title: 'Travel Series',
    videoId: 'zp4iIAx0qVc',
    category: 'travel',
    description: 'Travel documentary series',
  },
  {
    title: 'Corporate Vision',
    videoId: 'ZN2Ktk-2At0',
    category: 'brands',
    description: 'Company vision film',
  },
  {
    title: 'Brand Story',
    videoId: 'Ox8Vvx8ENU0',
    category: 'brands',
    description: 'Corporate narrative',
  },
  {
    title: 'Marketing Campaign',
    videoId: 'dOFntcrHfdk',
    category: 'brands',
    description: 'Strategic campaign film',
  },
  {
    title: 'Brand Initiative',
    videoId: '5mpwROnf8_k',
    category: 'brands',
    description: 'Corporate initiative film',
  },
  {
    title: 'Innovation Story',
    videoId: '0_tEdB59LhY',
    category: 'brands',
    description: 'Technology innovation film',
  },
  {
    title: 'Travel Documentary',
    videoId: 'jxDc7icF-Lg',
    category: 'travel',
    description: 'Travel series episode',
  },
  {
    title: 'Brand Campaign',
    videoId: 's7xQTc3aP8U',
    category: 'brands',
    description: 'Marketing campaign',
  },
  {
    title: 'Corporate Event',
    videoId: 'ClL445zPZGo',
    category: 'events',
    description: 'Business event coverage',
  },
  {
    title: 'Brand Story',
    videoId: 'p9zWIfGkFuo',
    category: 'brands',
    description: 'Corporate storytelling',
  },
  // {
  //   title: 'Travel Series',
  //   videoId: 'DYfE6UNlYNQ',
  //   category: 'travel',
  //   description: 'Travel documentary',
  // },
  {
    title: 'Corporate Film',
    videoId: 'DmQqS1dIh3U',
    category: 'brands',
    description: 'Business showcase',
  },
  {
    title: 'Brand Campaign',
    videoId: 'VUh78cxA_04',
    category: 'brands',
    description: 'Marketing initiative',
  },
  {
    title: 'Corporate Vision',
    videoId: 'nWRGCuiJMy8',
    category: 'brands',
    description: 'Company showcase',
  },
  {
    title: 'Brand Story',
    videoId: 'BSg4EjWPq8E',
    category: 'brands',
    description: 'Corporate narrative',
  },
  {
    title: 'Marketing Campaign',
    videoId: '5WpZLFnn9UQ',
    category: 'brands',
    description: 'Strategic campaign',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Works' },
  { id: 'brands', label: 'Brand Films' },
  { id: 'shows', label: 'Web Series' },
  { id: 'events', label: 'Events' },
  { id: 'music', label: 'Music Videos' },
  { id: 'travel', label: 'Travel' },
  { id: 'films', label: 'Films' },
];
